[package]
name = "pause_process"
version = "0.1.0"
authors = ["Wim"]

[dependencies.winapi]
version = "0.3.6"
features = ["winuser", "errhandlingapi", "tlhelp32", "processthreadsapi", "handleapi", "winnt"]